import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="fixed top-0 left-0 w-full  text-black px-10 py-10hadow-md z-10 bg-white">
      <div className="max-w-7xl mx-auto flex items-center justify-between px-4">
        {/* Branding */}
        <div className="text-lg font-semibold">TestersPlaybook</div>

        {/* Navigation Links */}
        <nav className="flex items-center gap-6">
          <a href="/" className="hover:underline">
            Dashboard
          </a>
          <a href="/projects" className="hover:underline">
            Projects
          </a>
          <a href="/account" className="hover:underline">
            Account
          </a>
        </nav>
      </div>
    </header>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased pt-5px-10`}
      >
        <Header />
        {/* <main className="mt-6 max-w-5xl mx-auto pt-20 px-2"> */}
        <main >
          {children}
        </main>
      </body>
    </html>
  );
}
